=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/descripteur.dtd
<!-- DTD for the Concepts and their PT in the language DESCRIPTEUR/@LNG -->
<!ELEMENT DESCRIPTEUR (RECORD+)>
<!ATTLIST DESCRIPTEUR
			LNG				CDATA		#REQUIRED
			VERSION			CDATA		#REQUIRED >
<!-- version is the EUROVOC release number; LNG is the language of the PT (LIBELLE) in the document instance -->

<!ELEMENT RECORD (DESCRIPTEUR_ID, LIBELLE, DEF?)>
<!-- Each record contains
- one concept ID  (ev:ThesaurusConcept/dc:identifier)
- its PT [LIBELLE]
- the occasional definition note with that PT [DEF]
-->

<!ELEMENT DESCRIPTEUR_ID	(#PCDATA)><!-- ev:ThesaurusConcept/dc:identifer -->
<!-- The concept identifier
 ev:ThesaurusConcept/dc:identifer 
-->
<!ELEMENT LIBELLE			(#PCDATA)>
<!-- the PT of the concept
ev:ThesaurusConcept/xl:prefLabel/xl:literalForm[@xml:lang = /DESCRIPTEUR/@LNG] 

Each PT
- must appear in the alphabetic index of that language.
- if the concept is a country with a country code, the country code must be given in the index (descripteur_thesaurus_pdf.dtd) - ??
- must list the micro thesaurus (descripteur_thesaurus_pdf.dtd and thesaurus.dtd) - MT
- must list the occasional socpe notes in that language (scope_note_pdf.dtd) - SN
- must list the occasional history notes in that language (scope_note_pdf.dtd) - HN
- must list the occasional definition notes in that language (DEF) - DEF
- must list the occasional synonyms (used_for_pdf.dtd) - UF
- must list the occasional compound synonyms (compound_non_pt.dtd) - UF+
- must list the associative relations (relation_rt.dtd) language independent (use PT) - RT
- must list the hierarchical narrower relations (inverse of relation_bt.dtd) language independent (use PT) - NT
- must list the occasional use-instead concept (relation_ui_pdf.dtd) language independent - UI
-->
<!ATTLIST LIBELLE
			FORM		(fullname | shortname | acronym)		#IMPLIED>
<!-- occasional indication of the form of a term -->

<!ELEMENT DEF				(#PCDATA)>
		<!-- string(ev:ThesaurusConcept/xl:prefLabel[ev:language = /DESCRIPTEUR/@LNG]/skos:definition) -->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/desc_ga.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DESCRIPTEUR SYSTEM "descripteur.dtd">
<DESCRIPTEUR LNG="ga" VERSION="4.5"><RECORD><DESCRIPTEUR_ID>1002</DESCRIPTEUR_ID><LIBELLE>infheistíocht fhadtéarmach</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1019</DESCRIPTEUR_ID><LIBELLE>An Fhionlainn</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1022</DESCRIPTEUR_ID><LIBELLE>Ciste Leanaí na Náisiún Aontaithe</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1024</DESCRIPTEUR_ID><LIBELLE>An Ghníomhaireacht Idirnáisiúnta Fuinnimh</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1034</DESCRIPTEUR_ID><LIBELLE>an Ghníomhaireacht Idirnáisiúnta d'Fhuinneamh Adamhach</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1043</DESCRIPTEUR_ID><LIBELLE>An Ciste Airgeadaíochta Idirnáisiúnta</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1044</DESCRIPTEUR_ID><LIBELLE>AISS</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1056</DESCRIPTEUR_ID><LIBELLE>Ciste Forbraíochta Réigiúnaí na hEorpa</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1058</DESCRIPTEUR_ID><LIBELLE>An Ciste Eorpach Airgeadaíochta</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1085</DESCRIPTEUR_ID><LIBELLE>An Fhrainc</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1086</DESCRIPTEUR_ID><LIBELLE>roinn agus réigiún thar lear de chuid na Fraince</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1087</DESCRIPTEUR_ID><LIBELLE>comhroinn Francach thar lear</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1094</DESCRIPTEUR_ID><LIBELLE>ALADI</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1100</DESCRIPTEUR_ID><LIBELLE>Friuli-Venezia Giulia</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>111</DESCRIPTEUR_ID><LIBELLE>Congo</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1123</DESCRIPTEUR_ID><LIBELLE>comhleá núicléach</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1124</DESCRIPTEUR_ID><LIBELLE>An Ghabúin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1125</DESCRIPTEUR_ID><LIBELLE>An Albáin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1128</DESCRIPTEUR_ID><LIBELLE>An Ghaimbia</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>113</DESCRIPTEUR_ID><LIBELLE>Connacht</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1136</DESCRIPTEUR_ID><LIBELLE>Comhaontú Ginearálta um Tharaifí agus Thrádáil</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>114</DESCRIPTEUR_ID><LIBELLE>Comhairle an Aontais Eorpaigh</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>115</DESCRIPTEUR_ID><LIBELLE>bord bainistíochta</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1150</DESCRIPTEUR_ID><LIBELLE>geografaíocht pholaitiúil</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1166</DESCRIPTEUR_ID><LIBELLE>Gána</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1177</DESCRIPTEUR_ID><LIBELLE>Alentejo</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>118</DESCRIPTEUR_ID><LIBELLE>An Chomhairle um Chomhar Cultúrtha</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1182</DESCRIPTEUR_ID><LIBELLE>An Ghréig</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1185</DESCRIPTEUR_ID><LIBELLE>Grenada</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1187</DESCRIPTEUR_ID><LIBELLE>Algarve</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1188</DESCRIPTEUR_ID><LIBELLE>An Ghraonlainn</LIBELLE><DEF>Críoch fhéinrialaithe de chuid na Danmhairge.</DEF></RECORD><RECORD><DESCRIPTEUR_ID>1195</DESCRIPTEUR_ID><LIBELLE>An Comhaontú Eorpach maidir le hiompar idirnáisiúnta earraí dainséaracha de bhót</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1196</DESCRIPTEUR_ID><LIBELLE>An Ailgéir</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>120</DESCRIPTEUR_ID><LIBELLE>ASPAC</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1208</DESCRIPTEUR_ID><LIBELLE>Guatamala</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>121</DESCRIPTEUR_ID><LIBELLE>Comhairle na Eorpa</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1216</DESCRIPTEUR_ID><LIBELLE>An Ghuine</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1217</DESCRIPTEUR_ID><LIBELLE>Guine Bhissau</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1218</DESCRIPTEUR_ID><LIBELLE>An Ghuine Mheánchiorclach</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1219</DESCRIPTEUR_ID><LIBELLE>An Ghuáin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1228</DESCRIPTEUR_ID><LIBELLE>Háití</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>123</DESCRIPTEUR_ID><LIBELLE>Comhairle Slándála na Náisiún Aontaithe</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1236</DESCRIPTEUR_ID><LIBELLE>Buircíne Fasó</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>124</DESCRIPTEUR_ID><LIBELLE>Conseil de tutelle ONU</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1242</DESCRIPTEUR_ID><LIBELLE>Tráth na gCeisteanna</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1245</DESCRIPTEUR_ID><LIBELLE>stair</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>125</DESCRIPTEUR_ID><LIBELLE>Comhairle Bhardais agus Réigiúin na hEorpa</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1252</DESCRIPTEUR_ID><LIBELLE>deimhniú</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1253</DESCRIPTEUR_ID><LIBELLE>Hondúras</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1255</DESCRIPTEUR_ID><LIBELLE>An Ungáir</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1277</DESCRIPTEUR_ID><LIBELLE>cothú ainmhithe</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>128</DESCRIPTEUR_ID><LIBELLE>An Chomhairle Eorpach</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1289</DESCRIPTEUR_ID><LIBELLE>Guam</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>129</DESCRIPTEUR_ID><LIBELLE>Conseil nordique</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1290</DESCRIPTEUR_ID><LIBELLE>Oileáin Mhuir nIocht</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1294</DESCRIPTEUR_ID><LIBELLE>Oileáin Fharó</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1299</DESCRIPTEUR_ID><LIBELLE>Ógh-Oileáin na Breataine</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1308</DESCRIPTEUR_ID><LIBELLE>Poblacht Dhaonlathach na Gearmáine</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1318</DESCRIPTEUR_ID><LIBELLE>An Ghearmáin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1338</DESCRIPTEUR_ID><LIBELLE>An India</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1355</DESCRIPTEUR_ID><LIBELLE>An Indinéis</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1410</DESCRIPTEUR_ID><LIBELLE>innealtóireacht mheicniúil</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1430</DESCRIPTEUR_ID><LIBELLE>Alsace</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1438</DESCRIPTEUR_ID><LIBELLE>tionscnamh reachtach</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1460</DESCRIPTEUR_ID><LIBELLE>ionstraim airgeadais (AE)</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1500</DESCRIPTEUR_ID><LIBELLE>An Iaráic</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1501</DESCRIPTEUR_ID><LIBELLE>An Iaráin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1504</DESCRIPTEUR_ID><LIBELLE>Éire</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1509</DESCRIPTEUR_ID><LIBELLE>An Íoslainn</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1510</DESCRIPTEUR_ID><LIBELLE>ISO</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1518</DESCRIPTEUR_ID><LIBELLE>Iosrael</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1519</DESCRIPTEUR_ID><LIBELLE>An Iodáil</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1522</DESCRIPTEUR_ID><LIBELLE>Iamáice</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1524</DESCRIPTEUR_ID><LIBELLE>An tSeapáin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1532</DESCRIPTEUR_ID><LIBELLE>An Iordáin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1549</DESCRIPTEUR_ID><LIBELLE>fíneáil</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1555</DESCRIPTEUR_ID><LIBELLE>An Chambóid</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1557</DESCRIPTEUR_ID><LIBELLE>An Chéinia</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1558</DESCRIPTEUR_ID><LIBELLE>leasú</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1559</DESCRIPTEUR_ID><LIBELLE>Cireabaití</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1560</DESCRIPTEUR_ID><LIBELLE>Cuáit</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1562</DESCRIPTEUR_ID><LIBELLE>marc cáilíochta</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1580</DESCRIPTEUR_ID><LIBELLE>teanga</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1584</DESCRIPTEUR_ID><LIBELLE>Laos</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1587</DESCRIPTEUR_ID><LIBELLE>Amérique</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1592</DESCRIPTEUR_ID><LIBELLE>reachtaíocht in aghaidh trustaí</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1606</DESCRIPTEUR_ID><LIBELLE>Amérique centrale</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1611</DESCRIPTEUR_ID><LIBELLE>Leosóta</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1613</DESCRIPTEUR_ID><LIBELLE>An Liobáin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1615</DESCRIPTEUR_ID><LIBELLE>Amérique du Nord</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1617</DESCRIPTEUR_ID><LIBELLE>An Libéir</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1624</DESCRIPTEUR_ID><LIBELLE>Amérique du Sud</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1632</DESCRIPTEUR_ID><LIBELLE>Amérique latine</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1639</DESCRIPTEUR_ID><LIBELLE>An Libia</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1649</DESCRIPTEUR_ID><LIBELLE>Lichtinstéin</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1657</DESCRIPTEUR_ID><LIBELLE>an Conradh Arabach</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1664</DESCRIPTEUR_ID><LIBELLE>Amnesty International</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1670</DESCRIPTEUR_ID><LIBELLE>teangeolaíocht</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>168</DESCRIPTEUR_ID><LIBELLE>EADI</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1696</DESCRIPTEUR_ID><LIBELLE>bogearraí</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1712</DESCRIPTEUR_ID><LIBELLE>Lucsamburg</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1727</DESCRIPTEUR_ID><LIBELLE>an Mhaisréic</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1729</DESCRIPTEUR_ID><LIBELLE>Madagascar</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1737</DESCRIPTEUR_ID><LIBELLE>lucht saothair</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>176</DESCRIPTEUR_ID><LIBELLE>Comhlachas Saorthrádála na hEorpa</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1766</DESCRIPTEUR_ID><LIBELLE>An Mhaláiv</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1767</DESCRIPTEUR_ID><LIBELLE>An Mhalaeisia</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1768</DESCRIPTEUR_ID><LIBELLE>Oileáin Mhaildíve</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1769</DESCRIPTEUR_ID><LIBELLE>Mailí</LIBELLE></RECORD><RECORD><DESCRIPTEUR_ID>1771</DESCRIPTEUR_ID><LIBELLE>Oileáin Fháclainne</LIBELLE><DEF>Críoch thar lear de chuid na Ríochta Aontaith
