=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/domaine.dtd
<!-- DTD pour le fichier des domaines  -->

<!ELEMENT DOMAINES (RECORD+)>

<!ELEMENT RECORD (DOMAINE_ID, LIBELLE)> <!-- ev:Domain -->

<!ELEMENT DOMAINE_ID		(#PCDATA)><!-- dc:identifer -->

<!ELEMENT LIBELLE			(#PCDATA)> <!-- skos:prefLabel[@xml:lang = /DOMAINES/@LNG] -->

<!ATTLIST DOMAINES

			LNG				CDATA		#REQUIRED
			VERSION			CDATA		#REQUIRED >
<!-- calculate version on change, initial value is config, algorithm is needed (date ?, thes version?) -->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_lt.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="lt" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>TARPTAUTINIAI SANTYKIAI</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EUROPOS SĄJUNGA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>TEISĖ</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>PREKYBA</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANSAI</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIALINIAI KLAUSIMAI</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>ŠVIETIMAS IR RYŠIAI</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>MOKSLAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>VERSLAS IR KONKURENCIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>UŽIMTUMAS IR DARBO SĄLYGOS</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORTAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>APLINKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>ŽEMĖS ŪKIS, MIŠKININKYSTĖ IR ŽUVININKYSTĖ</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>ŽEMĖS ŪKIO MAISTO PRODUKTAI</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>GAMYBA, TECHNOLOGIJOS IR MOKSLINIAI TYRIMAI</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGETIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>PRAMONĖ</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>TARPTAUTINĖS ORGANIZACIJOS</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_de.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="de" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITISCHES LEBEN</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>INTERNATIONALE BEZIEHUNGEN</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EUROPÄISCHE UNION</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>RECHT</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>WIRTSCHAFT</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>HANDEL</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANZWESEN</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOZIALE FRAGEN</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>BILDUNG UND KOMMUNIKATION</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>WISSENSCHAFTEN</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>UNTERNEHMEN UND WETTBEWERB</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>BESCHÄFTIGUNG UND ARBEITSBEDINGUNGEN</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>VERKEHR</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>UMWELT</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>LAND- UND FORSTWIRTSCHAFT, FISCHEREI</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>AGRARERZEUGNISSE UND LEBENSMITTEL</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUKTION, TECHNOLOGIE UND FORSCHUNG</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>INTERNATIONALE ORGANISATIONEN</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_hr.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="hr" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>MEĐUNARODNI ODNOSI</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EUROPSKA UNIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>PRAVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>TRGOVINA</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANCIJE</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>DRUŠTVENA PITANJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>OBRAZOVANJE I KOMUNIKACIJE</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>ZNANOST</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>POSLOVANJE I KONKURENCIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ZAPOŠLJAVANJE I RADNI UVJETI</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>PRIJEVOZ</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>OKOLIŠ</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>POLJOPRIVREDA, ŠUMARSTVO I RIBARSTVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>POLJOPRIVREDNO-PREHRAMBENA INDUSTRIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PROIZVODNJA, TEHNOLOGIJA I ISTRAŽIVANJE</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>ZEMLJOPIS</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>MEĐUNARODNE ORGANIZACIJE</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_sr.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="sr" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>ПОЛИТИКА</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>МЕЂУНАРОДНИ ОДНОСИ</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>ЕВРОПСКА УНИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>ПРАВО</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ЕКОНОМИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>ТРГОВИНА</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>ФИНАНСИЈЕ</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>ДРУШТВЕНА ПИТАЊА</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>ОБРАЗОБАЊЕ И КОМУНИКАЦИЈЕ</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>НАУКА</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>ПОСЛОВАЊЕ И КОНКУРЕНЦИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ЗАПОШЉАВАЊЕ И РАДНИ УСЛОВИ</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>ПРЕВОЗ</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ЖИВОТНА СРЕДИНА</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>ПОЉОПРИВРЕДА, ШУМАРСТВО И РИБАРСТВО</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>ПОЉОПРИВРЕДНО-ПРЕХРАМБЕНА ИНДУСТРИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>ПРОИЗВОДЊА, ТЕХНОЛОГИЈА И ИСТРАЖИВАЊЕ</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>EНЕРГИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>ИНДУСТРИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>ГЕОГРАФИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>МЕЂУНАРОДНЕ ОРГАНИЗАЦИЈЕ</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_sq.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="sq" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>MARRËDHËNIET NDËRKOMBËTARE</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>BASHKIMI EUROPIAN</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>LIGJ</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMI</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>TREGTI</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANCË</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>ÇËSHTJE SOCIALE</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>ARSIMI DHE KOMUNIKIMI</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>SHKENCA</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>BIZNESI DHE KOKURRENCA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>PUNËSIMI DHE KUSHTET E PUNËS</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORTI</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>MJEDISI</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>BUJQËSIA, PYJET DHE PESHKIMI</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>PRODUKTET AGRUSHQIMORE</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODHIMI, TEKNOLOGJIA DHE KËRKIMI</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGJIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GJEOGRAFI</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ORGANIZATAT NDËRKOMBËTARE</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_mk.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="mk" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>ПОЛИТИКА</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>МЕЃУНАРОДНИ ОДНОСИ</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>ЕВРОПСКА УНИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>ПРАВО</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ЕКОНОМИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>ТРГОВИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>ФИНАНСИИ</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>СОЦИЈАЛНИ ПРАШАЊА</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>ОБРАЗОВАНИЕ И КОМУНИКАЦИИ</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>НАУКА</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>ДЕЛОВНОСТ И КОНКУРЕНЦИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ВРАБОТУВАЊЕ И РАБОТНИ УСЛОВИ</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>ТРАНСПОРТ</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ЖИВОТНА СРЕДИНА</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>ЗЕМЈОДЕЛСТВО, ШУМАРСТВО И РИБАРСТВО</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>ЗЕМЈОДЕЛСКО-ПРЕХРАНБЕНИ ПРОИЗВОДИ</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>ПРОИЗВОДСТВО, ТЕХНОЛОГИЈА И ИСТРАЖУВАЊЕ</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ЕНЕРГИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>ИНДУСТРИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>ГЕОГРАФИЈА</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>МЕЃУНАРОДНИ ОРГАНИЗАЦИИ</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_el.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="el" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>ΠΟΛΙΤΙΚΗ</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>ΔΙΕΘΝΕΙΣ ΣΧΕΣΕΙΣ</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>ΕΥΡΩΠΑΪΚΗ ΕΝΩΣΗ</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>ΔΙΚΑΙΟ</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ΟΙΚΟΝΟΜΙΚΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>ΕΜΠΟΡΙΟ</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>ΔΗΜΟΣΙΟΝΟΜΙΚΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>ΚΟΙΝΩΝΙΚΑ ΘΕΜΑΤΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>ΕΚΠΑΙΔΕΥΣΗ ΚΑΙ ΕΠΙΚΟΙΝΩΝΙΕΣ</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>ΕΠΙΣΤΗΜΕΣ</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>ΕΠΙΧΕΙΡΗΣΕΙΣ ΚΑΙ ΑΝΤΑΓΩΝΙΣΜΟΣ</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ΑΠΑΣΧΟΛΗΣΗ ΚΑΙ ΣΥΝΘΗΚΕΣ ΕΡΓΑΣΙΑΣ</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>ΜΕΤΑΦΟΡΕΣ</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ΠΕΡΙΒΑΛΛΟΝ</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>ΓΕΩΡΓΙΑ, ΔΑΣΟΚΟΜΙΑ ΚΑΙ ΑΛΙΕΙΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>ΓΕΩΡΓΙΚΑ ΠΡΟΪΟΝΤΑ ΔΙΑΤΡΟΦΗΣ</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>ΠΑΡΑΓΩΓΗ, ΤΕΧΝΟΛΟΓΙΑ ΚΑΙ ΕΡΕΥΝΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ΕΝΕΡΓΕΙΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>ΒΙΟΜΗΧΑΝΙΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>ΓΕΩΓΡΑΦΙΑ</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ΔΙΕΘΝΕΙΣ ΟΡΓΑΝΙΣΜΟΙ</LIBELLE></RECORD></DOMAINES>
