=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/domaine.dtd
<!-- DTD pour le fichier des domaines  -->

<!ELEMENT DOMAINES (RECORD+)>

<!ELEMENT RECORD (DOMAINE_ID, LIBELLE)> <!-- ev:Domain -->

<!ELEMENT DOMAINE_ID		(#PCDATA)><!-- dc:identifer -->

<!ELEMENT LIBELLE			(#PCDATA)> <!-- skos:prefLabel[@xml:lang = /DOMAINES/@LNG] -->

<!ATTLIST DOMAINES

			LNG				CDATA		#REQUIRED
			VERSION			CDATA		#REQUIRED >
<!-- calculate version on change, initial value is config, algorithm is needed (date ?, thes version?) -->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_mt.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="mt" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>RELAZZJONIJIET INTERNAZZJONALI</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>UNJONI EWROPEA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>DRITT</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>KUMMERĊ</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANZI</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>KWISTJONIJIET SOĊJALI</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>EDUKAZZJONI U KOMUNIKAZZJONI</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>XJENZA</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>IMPRIŻA U KOMPETIZZJONI</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>IMPJIEGI U KUNDIZZJONIJIET TAX-XOGĦOL</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRASPORT</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>AMBJENT</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>AGRIKOLTURA, FORESTRIJA U SAJD</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>PRODOTTI AGROALIMENTARI</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUZZJONI, TEKNOLOĠIJA U RIĊERKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERĠIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>ĠEOGRAFIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ORGANIZZAZZJONIJIET INTERNAZZJONALI</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_en.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="en" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITICS</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>INTERNATIONAL RELATIONS</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EUROPEAN UNION</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>LAW</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ECONOMICS</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>TRADE</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANCE</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIAL QUESTIONS</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>EDUCATION AND COMMUNICATIONS</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>SCIENCE</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>BUSINESS AND COMPETITION</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>EMPLOYMENT AND WORKING CONDITIONS</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORT</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ENVIRONMENT</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>AGRICULTURE, FORESTRY AND FISHERIES</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>AGRI-FOODSTUFFS</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUCTION, TECHNOLOGY AND RESEARCH</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGY</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRY</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAPHY</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>INTERNATIONAL ORGANISATIONS</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_pt.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="pt" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>ATIVIDADE POLÍTICA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>RELAÇÕES INTERNACIONAIS</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>UNIÃO EUROPEIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>DIREITO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ECONOMIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>INTERCÂMBIOS ECONÓMICOS E COMERCIAIS</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANÇAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>QUESTÕES SOCIAIS</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>EDUCAÇÃO E COMUNICAÇÃO</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>CIÊNCIAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>EMPRESAS E CONCORRÊNCIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>EMPREGO E TRABALHO</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORTES</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>MEIO AMBIENTE</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>AGRICULTURA, SILVICULTURA E PESCA</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>AGROALIMENTAR</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUÇÃO, TECNOLOGIA E INVESTIGAÇÃO</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDÚSTRIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ORGANIZAÇÕES INTERNACIONAIS</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_hu.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="hu" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>NEMZETKÖZI KAPCSOLATOK</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EURÓPAI UNIÓ</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>JOG</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>KÖZGAZDASÁGTAN</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>KERESKEDELEM</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>PÉNZÜGYEK</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>TÁRSADALMI KÉRDÉSEK</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>OKTATÁS ÉS KOMMUNIKÁCIÓ</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>TUDOMÁNY</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>VÁLLALKOZÁSOK ÉS VERSENY</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>FOGLALKOZTATÁS ÉS MUNKAKÖRÜLMÉNYEK</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>KÖZLEKEDÉS</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>KÖRNYEZET</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>MEZŐGAZDASÁG, ERDÉSZET ÉS HALÁSZAT</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>AGRÁRÉLELMISZER-IPAR</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>TERMELÉS, TECHNOLÓGIA ÉS KUTATÁS</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>IPAR</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>FÖLDRAJZ</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>NEMZETKÖZI SZERVEZETEK</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_it.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="it" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>VITA POLITICA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>RELAZIONI INTERNAZIONALI</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>UNIONE EUROPEA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>DIRITTO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ECONOMIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>SCAMBI ECONOMICI E COMMERCIALI</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANZE</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>QUESTIONI SOCIALI</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>ISTRUZIONE E COMUNICAZIONE</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>SCIENZE</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>IMPRESA E CONCORRENZA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>OCCUPAZIONE E LAVORO</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRASPORTO</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>AMBIENTE</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>AGRICOLTURA, SILVICOLTURA E PESCA</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>AGROALIMENTARE</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUZIONE, TECNOLOGIA E RICERCA</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ORGANIZZAZIONI INTERNAZIONALI</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_es.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="es" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>VIDA POLÍTICA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>RELACIONES INTERNACIONALES</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>UNIÓN EUROPEA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>DERECHO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ECONOMÍA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>INTERCAMBIOS ECONÓMICOS Y COMERCIALES</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>ASUNTOS FINANCIEROS</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>ASUNTOS SOCIALE</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>EDUCACIÓN Y COMUNICACIÓN</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>CIENCIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>EMPRESA Y COMPETENCIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>TRABAJO Y EMPLEO</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORTES</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>MEDIO AMBIENTE</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>AGRICULTURA, SILVICULTURA Y PESCA</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>SECTOR AGROALIMENTARIO</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUCCIÓN, TECNOLOGÍA E INVESTIGACIÓN</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGÍA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFÍA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ORGANIZACIONES INTERNACIONALES</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_cs.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="cs" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITICKÝ ŽIVOT</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>MEZINÁRODNÍ VZTAHY</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EVROPSKÁ UNIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>PRÁVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>OBCHOD</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANČNICTVÍ</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIÁLNÍ OTÁZKY</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>VZDĚLÁVÁNÍ A KOMUNIKACE</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>VĚDA</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>PODNIKÁNÍ A HOSPODÁŘSKÁ SOUTĚŽ</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ZAMĚSTNANOST A PRÁCE</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>DOPRAVA</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ŽIVOTNÍ PROSTŘEDÍ</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>ZEMĚDĚLSTVÍ, LESNICTVÍ A RYBÁŘSTVÍ</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>ZEMĚDĚLSTVÍ A VÝŽIVA</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>VÝROBA, TECHNOLOGIE A VÝZKUM</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGETIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>PRŮMYSL</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>MEZINÁRODNÍ ORGANIZACE</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_et.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="et" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLIITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>RAHVUSVAHELISED SUHTED</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EUROOPA LIIT</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>ÕIGUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>MAJANDUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>KAUBANDUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>RAHANDUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOTSIAALKÜSIMUSED</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>HARIDUS JA KOMMUNIKATSIOON</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>TEADUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>ETTEVÕTLUS JA KONKURENTS</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>TÖÖHÕIVE JA TÖÖTINGIMUSED</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORT</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>KESKKOND</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>PÕLLUMAJANDUS, METSANDUS JA KALANDUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>TOIDUAINETÖÖSTUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>TOOTMINE, TEHNOLOOGIA JA UURIMINE</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGEETIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>TÖÖSTUS</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAAFIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>RAHVUSVAHELISED ORGANISATSIOONID</LIBELLE></RECORD></DOMAINES>
