=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/domaine.dtd
<!-- DTD pour le fichier des domaines  -->

<!ELEMENT DOMAINES (RECORD+)>

<!ELEMENT RECORD (DOMAINE_ID, LIBELLE)> <!-- ev:Domain -->

<!ELEMENT DOMAINE_ID		(#PCDATA)><!-- dc:identifer -->

<!ELEMENT LIBELLE			(#PCDATA)> <!-- skos:prefLabel[@xml:lang = /DOMAINES/@LNG] -->

<!ATTLIST DOMAINES

			LNG				CDATA		#REQUIRED
			VERSION			CDATA		#REQUIRED >
<!-- calculate version on change, initial value is config, algorithm is needed (date ?, thes version?) -->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_pl.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="pl" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>ŻYCIE POLITYCZNE</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>STOSUNKI MIĘDZYNARODOWE</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>UNIA EUROPEJSKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>PRAWO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>HANDEL</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANSE</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>ZAGADNIENIA SPOŁECZNE</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>OŚWIATA I KOMUNIKACJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>NAUKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>PRZEDSIĘBIORSTWO I KONKURENCJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ZATRUDNIENIE I PRACA</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORT</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ŚRODOWISKO</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>ROLNICTWO, LEŚNICTWO I RYBOŁÓWSTWO</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>SEKTOR ROLNO-SPOŻYWCZY</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUKCJA, TECHNOLOGIA I BADANIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>PRZEMYSŁ</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ORGANIZACJE MIĘDZYNARODOWE</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_da.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="da" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIK</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>INTERNATIONALE RELATIONER</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>DEN EUROPÆISKE UNION</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>LOVBESTEMMELSER</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ØKONOMI</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>ØKONOMISK OG HANDELSMÆSSIGT SAMKVEM</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANSER</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIALE SPØRGSMÅL</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>UDDANNELSE OG KOMMUNIKATION</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>VIDENSKAB</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>VIRKSOMHEDER OG KONKURRENCE</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ARBEJDE OG BESKÆFTIGELSE</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORT</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>MILJØ</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>LANDBRUG, SKOVBRUG OG FISKERI</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>LANDBRUGSVAREINDUSTRI</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUKTION, TEKNOLOGI OG FORSKNING</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGI</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRI</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFI</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>INTERNATIONALE ORGANISATIONER</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_lv.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="lv" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>STARPTAUTISKĀS ATTIECĪBAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EIROPAS SAVIENĪBA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>TIESĪBAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>TIRDZNIECĪBA</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANSES</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIĀLIE JAUTĀJUMI</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>IZGLĪTĪBA UN KOMUNIKĀCIJAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>ZINĀTNE</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>UZŅĒMĒJDARBĪBA UN KONKURENCE</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>NODARBINĀTĪBA UN DARBA APSTĀKĻI</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORTS</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>VIDE</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>LAUKSAIMNIECĪBA, MEŽSAIMNIECĪBA UN ZVEJNIECĪBA</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>PĀRTIKAS RAŽOŠANA</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>RAŽOŠANA, TEHNOLOĢIJA UN PĒTNIECĪBA</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERĢĒTIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>RŪPNIECĪBA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>ĢEOGRĀFIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>STARPTAUTISKĀS ORGANIZĀCIJAS</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_fr.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="fr" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>VIE POLITIQUE</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>RELATIONS INTERNATIONALES</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>UNION EUROPÉENNE</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>DROIT</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>ÉCONOMIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>ÉCHANGES ÉCONOMIQUES ET COMMERCIAUX</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANCES</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>QUESTIONS SOCIALES</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>ÉDUCATION ET COMMUNICATION</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>SCIENCES</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>ENTREPRISE ET CONCURRENCE</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>EMPLOI ET TRAVAIL</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORTS</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ENVIRONNEMENT</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>AGRICULTURE, SYLVICULTURE ET PÊCHE</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>AGRO-ALIMENTAIRE</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUCTION, TECHNOLOGIE ET RECHERCHE</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ÉNERGIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GÉOGRAPHIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>ORGANISATIONS INTERNATIONALES</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_ga.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="ga" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLAITÍOCHT</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>CAIDREAMH IDIRNÁISIÚNTA</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>AN TAONTAS EORPACH</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>DLÍ</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EACNAMAÍOCHT</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>TRÁDÁIL</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>AIRGEADAS</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIAL QUESTIONS</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>EDUCATION AND COMMUNICATIONS</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>EOLAÍOCHT</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>BUSINESS AND COMPETITION</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>EMPLOYMENT AND WORKING CONDITIONS</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORT</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>COMHSHAOL</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>AGRICULTURE, FORESTRY AND FISHERIES</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>AGRI-FOODSTUFFS</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUCTION, TECHNOLOGY AND RESEARCH</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>FUINNEAMH</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>TIONSCAL</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>TÍREOLAÍOCHT</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>INTERNATIONAL ORGANISATIONS</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_sk.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="sk" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>MEDZINÁRODNÉ VZŤAHY</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EURÓPSKA ÚNIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>PRÁVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>OBCHOD</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANCIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIÁLNE OTÁZKY</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>VZDELANIE A KOMUNIKÁCIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>VEDA</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>PODNIKANIE A SÚŤAŽ</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ZAMESTNANIE A PRACOVNÉ PODMIENKY</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>DOPRAVA</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>ŽIVOTNÉ PROSTREDIE</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>POĽNOHOSPODÁRSTVO, LESNÍCTVO A RYBÁRSTVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>POTRAVINÁRSTVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>VÝROBA, TECHNOLÓGIA A VÝSKUM</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>PRIEMYSEL</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>MEDZINÁRODNÉ ORGANIZÁCIE</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_sl.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="sl" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>MEDNARODNI ODNOSI</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EVROPSKA UNIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>PRAVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>GOSPODARSTVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>TRGOVINA</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANCE</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>DRUŽBENA IN SOCIALNA VPRAŠANJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>IZOBRAŽEVANJE IN KOMUNIKACIJE</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>ZNANOST</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>POSLOVANJE IN KONKURENCA</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>ZAPOSLOVANJE IN DELOVNE RAZMERE</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>PROMET</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>OKOLJE</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>KMETIJSTVO, GOZDARSTVO IN RIBIŠTVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>KMETIJSKO ŽIVILSTVO</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PROIZVODNJA, TEHNOLOGIJA IN RAZISKOVANJE</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGETIKA</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFIJA</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>MEDNARODNE ORGANIZACIJE</LIBELLE></RECORD></DOMAINES>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/dom_sv.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE DOMAINES SYSTEM "domaine.dtd">
<DOMAINES LNG="sv" VERSION="4.5"><RECORD><DOMAINE_ID>04</DOMAINE_ID><LIBELLE>POLITIK</LIBELLE></RECORD><RECORD><DOMAINE_ID>08</DOMAINE_ID><LIBELLE>INTERNATIONELLA FÖRBINDELSER</LIBELLE></RECORD><RECORD><DOMAINE_ID>10</DOMAINE_ID><LIBELLE>EUROPEISKA UNIONEN</LIBELLE></RECORD><RECORD><DOMAINE_ID>12</DOMAINE_ID><LIBELLE>LAG OCH RÄTT</LIBELLE></RECORD><RECORD><DOMAINE_ID>16</DOMAINE_ID><LIBELLE>EKONOMI</LIBELLE></RECORD><RECORD><DOMAINE_ID>20</DOMAINE_ID><LIBELLE>HANDEL OCH AFFÄRSVERKSAMHET</LIBELLE></RECORD><RECORD><DOMAINE_ID>24</DOMAINE_ID><LIBELLE>FINANSER</LIBELLE></RECORD><RECORD><DOMAINE_ID>28</DOMAINE_ID><LIBELLE>SOCIALA FRÅGOR</LIBELLE></RECORD><RECORD><DOMAINE_ID>32</DOMAINE_ID><LIBELLE>UTBILDNING OCH KOMMUNIKATION</LIBELLE></RECORD><RECORD><DOMAINE_ID>36</DOMAINE_ID><LIBELLE>VETENSKAP</LIBELLE></RECORD><RECORD><DOMAINE_ID>40</DOMAINE_ID><LIBELLE>FÖRETAG OCH KONKURRENS</LIBELLE></RECORD><RECORD><DOMAINE_ID>44</DOMAINE_ID><LIBELLE>SYSSELSÄTTNING OCH ARBETE</LIBELLE></RECORD><RECORD><DOMAINE_ID>48</DOMAINE_ID><LIBELLE>TRANSPORT</LIBELLE></RECORD><RECORD><DOMAINE_ID>52</DOMAINE_ID><LIBELLE>MILJÖ</LIBELLE></RECORD><RECORD><DOMAINE_ID>56</DOMAINE_ID><LIBELLE>JORDBRUK, SKOGSBRUK OCH FISKE</LIBELLE></RECORD><RECORD><DOMAINE_ID>60</DOMAINE_ID><LIBELLE>JORDBRUKSLIVSMEDELSINDUSTRI</LIBELLE></RECORD><RECORD><DOMAINE_ID>64</DOMAINE_ID><LIBELLE>PRODUKTION, TEKNIK OCH FORSKNING</LIBELLE></RECORD><RECORD><DOMAINE_ID>66</DOMAINE_ID><LIBELLE>ENERGI</LIBELLE></RECORD><RECORD><DOMAINE_ID>68</DOMAINE_ID><LIBELLE>INDUSTRI</LIBELLE></RECORD><RECORD><DOMAINE_ID>72</DOMAINE_ID><LIBELLE>GEOGRAFI</LIBELLE></RECORD><RECORD><DOMAINE_ID>76</DOMAINE_ID><LIBELLE>INTERNATIONELLA ORGANISATIONER</LIBELLE></RECORD></DOMAINES>
