=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/relation_ui.dtd
<!-- DTD for use instead relations -->
<!ELEMENT RELATIONS_UI (RECORD+)>
<!ATTLIST RELATIONS_UI
			VERSION		CDATA		#REQUIRED >
<!-- The EUROVOC release number -->

<!ELEMENT RECORD (SOURCE_ID, CIBLE_ID)>
<!-- The relation between an obsolete concept and its replacement
Multiple record may exist for the same obsolete concept (because there may be more than one replacement
Replacements must be listead under the PT of the obsolete concept using UI: <value of replacing PT>

ev:ThesaurusConcept[ev:useInstead] -->

<!ELEMENT SOURCE_ID	(#PCDATA)>
<!-- The concept identifier of the obsolete term
ev:ThesaurusConcept[skos:broader/dc:identifer]/dc:identifer -->

<!ELEMENT CIBLE_ID	(#PCDATA)> 
<!-- The concept id of the replacing concept
ev:ThesaurusConcept[dc:identifier = SOURCE_ID]skos:broader/dc:identifer -->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/relation_ui.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE RELATIONS_UI SYSTEM "relation_ui.dtd">
<RELATIONS_UI VERSION="4.5"><RECORD><SOURCE_ID>1</SOURCE_ID><CIBLE_ID>8280</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1020</SOURCE_ID><CIBLE_ID>8283</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1096</SOURCE_ID><CIBLE_ID>8279</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1097</SOURCE_ID><CIBLE_ID>8279</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1121</SOURCE_ID><CIBLE_ID>726</CIBLE_ID></RECORD><RECORD><SOURCE_ID>119</SOURCE_ID><CIBLE_ID>6129</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1293</SOURCE_ID><CIBLE_ID>2362</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1297</SOURCE_ID><CIBLE_ID>2362</CIBLE_ID></RECORD><RECORD><SOURCE_ID>16</SOURCE_ID><CIBLE_ID>257</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1627</SOURCE_ID><CIBLE_ID>1634</CIBLE_ID></RECORD><RECORD><SOURCE_ID>1765</SOURCE_ID><CIBLE_ID>1767</CIBLE_ID></RECORD><RECORD><SOURCE_ID>181</SOURCE_ID><CIBLE_ID>1442</CIBLE_ID></RECORD><RECORD><SOURCE_ID>2074</SOURCE_ID><CIBLE_ID>8281</CIBLE_ID></RECORD><RECORD><SOURCE_ID>2103</SOURCE_ID><CIBLE_ID>2102</CIBLE_ID></RECORD><RECORD><SOURCE_ID>2164</SOURCE_ID><CIBLE_ID>5769</CIBLE_ID></RECORD><RECORD><SOURCE_ID>232</SOURCE_ID><CIBLE_ID>8279</CIBLE_ID></RECORD><RECORD><SOURCE_ID>2346</SOURCE_ID><CIBLE_ID>8407</CIBLE_ID></RECORD><RECORD><SOURCE_ID>2347</SOURCE_ID><CIBLE_ID>8407</CIBLE_ID></RECORD><RECORD><SOURCE_ID>2348</SOURCE_ID><CIBLE_ID>8407</CIBLE_ID></RECORD><RECORD><SOURCE_ID>2899</SOURCE_ID><CIBLE_ID>726</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3171</SOURCE_ID><CIBLE_ID>5751</CIBLE_ID></RECORD><RECORD><SOURCE_ID>334</SOURCE_ID><CIBLE_ID>7896</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3388</SOURCE_ID><CIBLE_ID>6282</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3388</SOURCE_ID><CIBLE_ID>6283</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3423</SOURCE_ID><CIBLE_ID>2595</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3716</SOURCE_ID><CIBLE_ID>428</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3719</SOURCE_ID><CIBLE_ID>8283</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3726</SOURCE_ID><CIBLE_ID>8280</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3752</SOURCE_ID><CIBLE_ID>8282</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3787</SOURCE_ID><CIBLE_ID>451912</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3791</SOURCE_ID><CIBLE_ID>1767</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3812</SOURCE_ID><CIBLE_ID>451912</CIBLE_ID></RECORD><RECORD><SOURCE_ID>3889</SOURCE_ID><CIBLE_ID>1767</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4014</SOURCE_ID><CIBLE_ID>349</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4015</SOURCE_ID><CIBLE_ID>449</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4020</SOURCE_ID><CIBLE_ID>2927</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4022</SOURCE_ID><CIBLE_ID>3102</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4035</SOURCE_ID><CIBLE_ID>6725</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4065</SOURCE_ID><CIBLE_ID>349</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4066</SOURCE_ID><CIBLE_ID>349</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4067</SOURCE_ID><CIBLE_ID>1451</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4124</SOURCE_ID><CIBLE_ID>447503</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4150</SOURCE_ID><CIBLE_ID>800</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4154</SOURCE_ID><CIBLE_ID>726</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4206</SOURCE_ID><CIBLE_ID>8283</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4244</SOURCE_ID><CIBLE_ID>4458</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4296</SOURCE_ID><CIBLE_ID>8279</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4297</SOURCE_ID><CIBLE_ID>8282</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4457</SOURCE_ID><CIBLE_ID>6284</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4459</SOURCE_ID><CIBLE_ID>7892</CIBLE_ID></RECORD><RECORD><SOURCE_ID>452085</SOURCE_ID><CIBLE_ID>c_4e3beee2</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4523</SOURCE_ID><CIBLE_ID>726</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4592</SOURCE_ID><CIBLE_ID>726</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4659</SOURCE_ID><CIBLE_ID>8283</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4678</SOURCE_ID><CIBLE_ID>8282</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4693</SOURCE_ID><CIBLE_ID>2074</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4693</SOURCE_ID><CIBLE_ID>8280</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4693</SOURCE_ID><CIBLE_ID>8281</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4776</SOURCE_ID><CIBLE_ID>4775</CIBLE_ID></RECORD><RECORD><SOURCE_ID>4826</SOURCE_ID><CIBLE_ID>2179</CIBLE_ID></RECORD><RECORD><SOURCE_ID>495</SOURCE_ID><CIBLE_ID>7896</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5022</SOURCE_ID><CIBLE_ID>451912</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5027</SOURCE_ID><CIBLE_ID>8279</CIBLE_ID></RECORD><RECORD><SOURCE_ID>503</SOURCE_ID><CIBLE_ID>726</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5051</SOURCE_ID><CIBLE_ID>438855</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5131</SOURCE_ID><CIBLE_ID>445178</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5285</SOURCE_ID><CIBLE_ID>5107</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5286</SOURCE_ID><CIBLE_ID>3722</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5366</SOURCE_ID><CIBLE_ID>2829</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5402</SOURCE_ID><CIBLE_ID>194</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5425</SOURCE_ID><CIBLE_ID>5769</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5434</SOURCE_ID><CIBLE_ID>1308</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5435</SOURCE_ID><CIBLE_ID>4620</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5452</SOURCE_ID><CIBLE_ID>5825</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5567</SOURCE_ID><CIBLE_ID>5824</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5641</SOURCE_ID><CIBLE_ID>5769</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5668</SOURCE_ID><CIBLE_ID>452085</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5680</SOURCE_ID><CIBLE_ID>5455</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5734</SOURCE_ID><CIBLE_ID>2785</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5758</SOURCE_ID><CIBLE_ID>6128</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5767</SOURCE_ID><CIBLE_ID>5769</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5815</SOURCE_ID><CIBLE_ID>440238</CIBLE_ID></RECORD><RECORD><SOURCE_ID>5931</SOURCE_ID><CIBLE_ID>4778</CIBLE_ID></RECORD><RECORD><SOURCE_ID>6015</SOURCE_ID><CIBLE_ID>2791</CIBLE_ID></RECORD><RECORD><SOURCE_ID>6157</SOURCE_ID><CIBLE_ID>8404</CIBLE_ID></RECORD><RECORD><SOURCE_ID>6248</SOURCE_ID><CIBLE_ID>7881</CIBLE_ID></RECORD><RECORD><SOURCE_ID>6250</SOURCE_ID><CIBLE_ID>6251</CIBLE_ID></RECORD><RECORD><SOURCE_ID>7194</SOURCE_ID><CIBLE_ID>349</CIBLE_ID></RECORD><RECORD><SOURCE_ID>727</SOURCE_ID><CIBLE_ID>726</CIBLE_ID></RECORD><RECORD><SOURCE_ID>8474</SOURCE_ID><CIBLE_ID>349</CIBLE_ID></RECORD><RECORD><SOURCE_ID>90</SOURCE_ID><CIBLE_ID>8404</CIBLE_ID></RECORD><RECORD><SOURCE_ID>979</SOURCE_ID><CIBLE_ID>450652</CIBLE_ID></RECORD><RECORD><SOURCE_ID>980</SOURCE_ID><CIBLE_ID>450658</CIBLE_ID></RECORD></RELATIONS_UI>
