=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/scope_note.dtd
<!-- DTD for scope notes and history notes of a concept  -->
<!ELEMENT SCOPE_NOTE (RECORD+)>
<!ATTLIST SCOPE_NOTE
			LNG					CDATA		#REQUIRED
			VERSION				CDATA		#REQUIRED >
<!-- language and EUROVOC release number -->

<!ELEMENT RECORD (DESCRIPTEUR_ID, (SN | HN | (SN, HN)) )>
<!-- The concept identifier and its related scope note or history note
ev:ThesaurusConcept[skos:scopeNote/ev:language = /DESCRIPTEUR/@LNG] 
-->

<!ELEMENT DESCRIPTEUR_ID	(#PCDATA)>
<!-- The ID of the concept
ev:ThesaurusConcept/dc:identifer -->

<!ELEMENT SN					(#PCDATA)>
<!-- The occasional scope note
string(ev:ThesaurusConcept/skos:scopeNote[ev:language = /DESCRIPTEUR/@LNG]/ev:noteLiteral) 
-->

<!ELEMENT HN					(#PCDATA)>
<!-- the occasional history note
string(ev:ThesaurusConcept/skos:historyNote[ev:language = /DESCRIPTEUR/@LNG]/ev:noteLiteral) 
-->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/sn_ga.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE SCOPE_NOTE SYSTEM "scope_note.dtd">
<SCOPE_NOTE LNG="ga" VERSION="4.5"><RECORD><DESCRIPTEUR_ID>2153</DESCRIPTEUR_ID><HN>Go dtí an 30.6.2009: Oifig Foilseachán Oifigiúil na gComhphobal Eorpach.</HN></RECORD><RECORD><DESCRIPTEUR_ID>256</DESCRIPTEUR_ID><HN>Roimh 1.12.2009: “Cúirt Iniúchóirí na gComhphobal Eorpach”.</HN></RECORD><RECORD><DESCRIPTEUR_ID>2820</DESCRIPTEUR_ID><HN>Stát féinrialaithe de chuid Ríocht na hÍsiltíre.</HN></RECORD><RECORD><DESCRIPTEUR_ID>333</DESCRIPTEUR_ID><HN>Stát féinrialaithe de chuid Ríocht na hÍsiltíre ó 10.10.2010 (Antillí na hÍsiltíre díscaoilte).</HN></RECORD><RECORD><DESCRIPTEUR_ID>4020</DESCRIPTEUR_ID><HN>Από από την έναρξη ισχύος της συνθήκης της Λισαβόνας (01.12.2009) και μετά να χρησιμοποιείται ο όρος «σύσταση (ΕE)».</HN></RECORD><RECORD><DESCRIPTEUR_ID>451885</DESCRIPTEUR_ID><HN>Stát féinrialaithe de chuid Ríocht na hÍsiltíre ó 10.10.2010 (Antillí na hÍsiltíre díscaoilte).</HN></RECORD><RECORD><DESCRIPTEUR_ID>4524</DESCRIPTEUR_ID><SN>Comhshocraíocht maidir le Trádáil Idirnáisiúnta Teicstílí</SN></RECORD><RECORD><DESCRIPTEUR_ID>5087</DESCRIPTEUR_ID><HN>Eagraíocht eacnamaíoch idir-rialtasach (1949-91) arna bunú ag an Aontas Sóivéadach, an Bhulgáir, an tSeicslóvaic, an Ungáir, an Pholainn agus an Rómáin. Le himeacht aimsire, bhí an Albáin (1949-87), Poblacht Dhaonlathach na Gearmáine (1950-90), an Mhongóil (1962), Cúba (1972) agus Vítneam (1978) páirteach ann, chomh maith leis an Iúgslaiv (1964) mar chomhbhall.</HN></RECORD><RECORD><DESCRIPTEUR_ID>5655</DESCRIPTEUR_ID><HN>Comhar polaitiúil agus réigiúnach arna bhunú ag Poblacht na Seicslóvaice, Poblacht na Polainne agus Poblacht na hUngáire i 1991. Tar éis don tSeicslóvaic titim as a chéile i 1993, tá ceithre thír pairteach ann toisc gur baill den chomhar iad an dá thír a d'eascair asti, mar atá Poblacht na Seice agus Poblacht na Slóvaice.</HN></RECORD><RECORD><DESCRIPTEUR_ID>7185</DESCRIPTEUR_ID><HN>Comhaontú saorthrádála a chruthaigh trí thír lár-Eorpacha (an tSeicslóvaic, an Pholainn is an Ungáir) i 1992 a thugann le chéile páirtithe an AE agus tíortha a d'iarr ballraíocht san AE. An 1 Eanáir 2007 is iad seo a leanas baill an ALECE/CEFTA:  an Chróit, Poblacht Iar-Iúgslavach na Macadóine, an tSeirbia, Montainéagró, an Albáin, an Bhoisnia-Heirseagaivéin, an Mholdóiv is an Chosaiv.</HN></RECORD><RECORD><DESCRIPTEUR_ID>7221</DESCRIPTEUR_ID><HN>Deireadh an tsainordaithe: 31.12.2008.</HN></RECORD><RECORD><DESCRIPTEUR_ID>8549</DESCRIPTEUR_ID><SN>Cabhraíonn an CED le hoibrithe a rinneadh iomarcach de dheasca na bpátrún domhanda trádála a bheith ag athrú chun post nua a fháil chomh tapa agus is féidir.</SN></RECORD></SCOPE_NOTE>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/sn_sr.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE SCOPE_NOTE SYSTEM "scope_note.dtd">
<SCOPE_NOTE LNG="sr" VERSION="4.5"><RECORD><DESCRIPTEUR_ID>1014</DESCRIPTEUR_ID><SN>финансирање које врши држава чланица</SN></RECORD><RECORD><DESCRIPTEUR_ID>1735</DESCRIPTEUR_ID><SN>правосудни званичник (судија, јавни тужилац, јавни правобранилац).</SN></RECORD><RECORD><DESCRIPTEUR_ID>1891</DESCRIPTEUR_ID><SN>Хибрид ражи и пшенице.</SN></RECORD><RECORD><DESCRIPTEUR_ID>1950</DESCRIPTEUR_ID><SN>променљивост места студија</SN></RECORD><RECORD><DESCRIPTEUR_ID>1988</DESCRIPTEUR_ID><SN>износ новчане надокнаде за девизно прилагођавање</SN></RECORD><RECORD><DESCRIPTEUR_ID>2643</DESCRIPTEUR_ID><SN>Најнижа цена по којој неки увозни пољопривредни производи могу бити продавани у ЕУ.</SN></RECORD><RECORD><DESCRIPTEUR_ID>2659</DESCRIPTEUR_ID><SN>Цена повлачења производа са тржишта.</SN></RECORD><RECORD><DESCRIPTEUR_ID>2661</DESCRIPTEUR_ID><SN>Цена по којој неки увозни пољопривредни производи могу бити продавани у ЕУ.</SN></RECORD><RECORD><DESCRIPTEUR_ID>2776</DESCRIPTEUR_ID><SN>Нарочито додавање воде.</SN></RECORD><RECORD><DESCRIPTEUR_ID>3269</DESCRIPTEUR_ID><SN>тарифа која је субвенционисана у корист домаћих превозника</SN></RECORD><RECORD><DESCRIPTEUR_ID>327</DESCRIPTEUR_ID><SN>Производња биља без земље.</SN></RECORD><RECORD><DESCRIPTEUR_ID>3270</DESCRIPTEUR_ID><SN>Снижена просечна цена ако се истовремено купи више различитх производа или услуга.</SN></RECORD><RECORD><DESCRIPTEUR_ID>3576</DESCRIPTEUR_ID><SN>поновна обрада запуштеног пољопривредног земљишта</SN></RECORD><RECORD><DESCRIPTEUR_ID>3738</DESCRIPTEUR_ID><SN>Мешавина бензина и алкохола.</SN></RECORD><RECORD><DESCRIPTEUR_ID>4032</DESCRIPTEUR_ID><SN>закључен априла 1965. године.</SN></RECORD><RECORD><DESCRIPTEUR_ID>4421</DESCRIPTEUR_ID><SN>технологија која може да побољша продуктивност традиционалних метода, а не захтева капитал или образовни ниво и обуку који су неопходни за напредну технологију</SN></RECORD><RECORD><DESCRIPTEUR_ID>4571</DESCRIPTEUR_ID><SN>Хибрид пшенице и ражи .</SN></RECORD><RECORD><DESCRIPTEUR_ID>4837</DESCRIPTEUR_ID><SN>вајарство, сликарство и архитектура</SN></RECORD><RECORD><DESCRIPTEUR_ID>4846</DESCRIPTEUR_ID><SN>до 1975. Дахомеј</SN></RECORD><RECORD><DESCRIPTEUR_ID>4966</DESCRIPTEUR_ID><SN>до 1989. Бурма</SN></RECORD><RECORD><DESCRIPTEUR_ID>5184</DESCRIPTEUR_ID><SN>производња радио и телевизијског програма</SN></RECORD><RECORD><DESCRIPTEUR_ID>5198</DESCRIPTEUR_ID><SN>снимање програма преко мреже</SN></RECORD><RECORD><DESCRIPTEUR_ID>5415</DESCRIPTEUR_ID><SN>Обухвата оптужницу, оптужни предлог и приватну тужбу.</SN></RECORD><RECORD><DESCRIPTEUR_ID>5839</DESCRIPTEUR_ID><SN>такса за заштиту животне средине</SN></RECORD><RECORD><DESCRIPTEUR_ID>6104</DESCRIPTEUR_ID><SN>депоновање код одговарајуће институције неколико бесплатних примерака књижевног или аудиовизуелног дела приликом њиховог објављивања или након објављивања.</SN></RECORD><RECORD><DESCRIPTEUR_ID>6130</DESCRIPTEUR_ID><SN>орган за решавање спорова у оквиру СТО</SN></RECORD><RECORD><DESCRIPTEUR_ID>6334</DESCRIPTEUR_ID><SN>међубанкарске каматне стопе израчунате уз помоћ Европског система централних банака</SN></RECORD><RECORD><DESCRIPTEUR_ID>6537</DESCRIPTEUR_ID><SN>породица у коју су један или оба родитеља довели децу из својих претходних веза</SN></RECORD><RECORD><DESCRIPTEUR_ID>6754</DESCRIPTEUR_ID><SN>производно или услужно предузеће основано да би се обезбедило укључивање незапослених у рад</SN></RECORD><RECORD><DESCRIPTEUR_ID>6913</DESCRIPTEUR_ID><SN>када предузеће издваја део свог пословања и преноси га на неко друго предузеће</SN></RECORD><RECORD><DESCRIPTEUR_ID>7353</DESCRIPTEUR_ID><SN>територија или администраривна јединица, која припада држави с којом нема географску везу</SN></RECORD><RECORD><DESCRIPTEUR_ID>7365</DESCRIPTEUR_ID><SN>Повреда обевезујућег управног прописа која обично повлачи управну казну</SN></RECORD><RECORD><DESCRIPTEUR_ID>7934</DESCRIPTEUR_ID><SN>Сарадња између влсти и предузетништва ради остваривања инфраструктурних пројеката или пружања услуга од општег значаја.</SN></RECORD><RECORD><DESCRIPTEUR_ID>7942</DESCRIPTEUR_ID><SN>Добровољно повезивање социјалних и еколошких обзира предузећа с њиховом комерцијалном делатносшћу и њиховим односима са заинтересованим странама.</SN></RECORD><RECORD><DESCRIPTEUR_ID>7947</DESCRIPTEUR_ID><SN>Нетражена порука послата електронским путем ради непосредног истраживања тржишта.</SN></RECORD><RECORD><DESCRIPTEUR_ID>7948</DESCRIPTEUR_ID><SN>Систем уверења и вредсности чланова једне организације који опредељује њихово понашање</SN></RECORD><RECORD><DESCRIPTEUR_ID>7949</DESCRIPTEUR_ID><SN>Скуп мера послодавца за помоћ запосленоме пред отказом да нађе запослење у другом предузећу.</SN></RECORD><RECORD><DESCRIPTEUR_ID>7951</DESCRIPTEUR_ID><SN>Економија заснивана на знању и технолошким иновацијама,што омогућава заснивање мреже стручности.</SN></RECORD><RECORD><DESCRIPTEUR_ID>7955</DESCRIPTEUR_ID><SN>Необликована ћелија ембриона, фетуса или одраслих лица, која има способност да се дели, преобликује и размножава</SN></RECORD></SCOPE_NOTE>

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/sn_mk.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE SCOPE_NOTE SYSTEM "scope_note.dtd">
<SCOPE_NOTE LNG="mk" VERSION="4.5"><RECORD><DESCRIPTEUR_ID>3171</DESCRIPTEUR_ID><SN>номенклатура на стоки за надворешнотрговска статистика на Заедницата и статистика за трговијата меѓу државите членки</SN></RECORD><RECORD><DESCRIPTEUR_ID>361</DESCRIPTEUR_ID><SN>законско пренесување на правото на одлучување за одредени области од централната власт на пониските локални органи</SN></RECORD><RECORD><DESCRIPTEUR_ID>6151</DESCRIPTEUR_ID><SN>територија на државите членки кои го имаат усвоено еврото како национално платежно средство</SN></RECORD><RECORD><DESCRIPTEUR_ID>744</DESCRIPTEUR_ID><SN>Обновливи или необновливи извори на енергија кои не ја загадуваат животната средина</SN></RECORD><RECORD><DESCRIPTEUR_ID>8479</DESCRIPTEUR_ID><SN>Институциски метод што ги користи механизмите на првиот столб на ЕУ, наспроти меѓувладиниот метод (односно меѓувладината соработка) којашто се користи за другите столбови.</SN></RECORD></SCOPE_NOTE>
