=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/thesaurus.dtd
<!-- DTD pour le fichier des thesaurus  -->

<!ELEMENT THESAURUS (RECORD+)>

<!ELEMENT RECORD (THESAURUS_ID, LIBELLE)><!-- ev:MicroThesaurus -->

<!ELEMENT THESAURUS_ID	(#PCDATA)><!-- dc:identifer -->

<!ELEMENT LIBELLE			(#PCDATA)> <!-- skos:prefLabel[@xml:lang = /THESAURUS/@LNG] -->

<!ATTLIST THESAURUS

			LNG				CDATA		#REQUIRED
			VERSION			CDATA		#REQUIRED >
<!-- calculate version on change, initial value is config, algorithm is needed (date ?, thes version?) -->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/thes_fi.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE THESAURUS SYSTEM "thesaurus.dtd">
<THESAURUS LNG="fi" VERSION="4.5"><RECORD><THESAURUS_ID>0406</THESAURUS_ID><LIBELLE>poliittinen kehys</LIBELLE></RECORD><RECORD><THESAURUS_ID>0411</THESAURUS_ID><LIBELLE>poliittinen puolue</LIBELLE></RECORD><RECORD><THESAURUS_ID>0416</THESAURUS_ID><LIBELLE>vaalimenettely ja äänestäminen</LIBELLE></RECORD><RECORD><THESAURUS_ID>0421</THESAURUS_ID><LIBELLE>parlamentti</LIBELLE></RECORD><RECORD><THESAURUS_ID>0426</THESAURUS_ID><LIBELLE>parlamentin työskentely</LIBELLE></RECORD><RECORD><THESAURUS_ID>0431</THESAURUS_ID><LIBELLE>poliittinen elämä ja yleinen turvallisuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>0436</THESAURUS_ID><LIBELLE>täytäntöönpanovalta ja julkinen hallinto</LIBELLE></RECORD><RECORD><THESAURUS_ID>0806</THESAURUS_ID><LIBELLE>kansainvälinen politiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>0811</THESAURUS_ID><LIBELLE>yhteistyöpolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>0816</THESAURUS_ID><LIBELLE>kansainvälinen tasapaino</LIBELLE></RECORD><RECORD><THESAURUS_ID>0821</THESAURUS_ID><LIBELLE>puolustus</LIBELLE></RECORD><RECORD><THESAURUS_ID>1006</THESAURUS_ID><LIBELLE>Euroopan unionin toimielimet ja unionin virkamieskunta</LIBELLE></RECORD><RECORD><THESAURUS_ID>1011</THESAURUS_ID><LIBELLE>Euroopan unionin oikeus</LIBELLE></RECORD><RECORD><THESAURUS_ID>1016</THESAURUS_ID><LIBELLE>Euroopan rakentamistyö</LIBELLE></RECORD><RECORD><THESAURUS_ID>1021</THESAURUS_ID><LIBELLE>EU:n talous- ja raha-asiat</LIBELLE></RECORD><RECORD><THESAURUS_ID>1206</THESAURUS_ID><LIBELLE>oikeuslähteet ja oikeuden alat</LIBELLE></RECORD><RECORD><THESAURUS_ID>1211</THESAURUS_ID><LIBELLE>siviilioikeus</LIBELLE></RECORD><RECORD><THESAURUS_ID>1216</THESAURUS_ID><LIBELLE>rikosoikeus</LIBELLE></RECORD><RECORD><THESAURUS_ID>1221</THESAURUS_ID><LIBELLE>oikeus</LIBELLE></RECORD><RECORD><THESAURUS_ID>1226</THESAURUS_ID><LIBELLE>oikeusorganisaatio</LIBELLE></RECORD><RECORD><THESAURUS_ID>1231</THESAURUS_ID><LIBELLE>kansainvälinen oikeus</LIBELLE></RECORD><RECORD><THESAURUS_ID>1236</THESAURUS_ID><LIBELLE>oikeudet ja vapaudet</LIBELLE></RECORD><RECORD><THESAURUS_ID>1606</THESAURUS_ID><LIBELLE>talouspolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>1611</THESAURUS_ID><LIBELLE>taloudellinen kasvu</LIBELLE></RECORD><RECORD><THESAURUS_ID>1616</THESAURUS_ID><LIBELLE>alueet ja aluepolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>1621</THESAURUS_ID><LIBELLE>talouden rakenne</LIBELLE></RECORD><RECORD><THESAURUS_ID>1626</THESAURUS_ID><LIBELLE>kansallinen tilinpito</LIBELLE></RECORD><RECORD><THESAURUS_ID>1631</THESAURUS_ID><LIBELLE>taloudellinen analyysi</LIBELLE></RECORD><RECORD><THESAURUS_ID>2006</THESAURUS_ID><LIBELLE>kauppapolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>2011</THESAURUS_ID><LIBELLE>tariffipolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>2016</THESAURUS_ID><LIBELLE>kauppa</LIBELLE></RECORD><RECORD><THESAURUS_ID>2021</THESAURUS_ID><LIBELLE>kansainvälinen kauppa</LIBELLE></RECORD><RECORD><THESAURUS_ID>2026</THESAURUS_ID><LIBELLE>kulutus</LIBELLE></RECORD><RECORD><THESAURUS_ID>2031</THESAURUS_ID><LIBELLE>kaupanpitäminen</LIBELLE></RECORD><RECORD><THESAURUS_ID>2036</THESAURUS_ID><LIBELLE>kaupallinen jakelu</LIBELLE></RECORD><RECORD><THESAURUS_ID>2406</THESAURUS_ID><LIBELLE>rahataloudelliset suhteet</LIBELLE></RECORD><RECORD><THESAURUS_ID>2411</THESAURUS_ID><LIBELLE>rahatalous</LIBELLE></RECORD><RECORD><THESAURUS_ID>2416</THESAURUS_ID><LIBELLE>luotto- ja rahoituslaitokset</LIBELLE></RECORD><RECORD><THESAURUS_ID>2421</THESAURUS_ID><LIBELLE>pääomien vapaa liikkuvuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>2426</THESAURUS_ID><LIBELLE>rahoitus ja investointi</LIBELLE></RECORD><RECORD><THESAURUS_ID>2431</THESAURUS_ID><LIBELLE>vakuutus</LIBELLE></RECORD><RECORD><THESAURUS_ID>2436</THESAURUS_ID><LIBELLE>julkistalous ja talousarviopolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>2441</THESAURUS_ID><LIBELLE>talousarvio</LIBELLE></RECORD><RECORD><THESAURUS_ID>2446</THESAURUS_ID><LIBELLE>verotus</LIBELLE></RECORD><RECORD><THESAURUS_ID>2451</THESAURUS_ID><LIBELLE>hinnat</LIBELLE></RECORD><RECORD><THESAURUS_ID>2806</THESAURUS_ID><LIBELLE>perhe</LIBELLE></RECORD><RECORD><THESAURUS_ID>2811</THESAURUS_ID><LIBELLE>siirtolaisuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>2816</THESAURUS_ID><LIBELLE>väestötiede ja väestö</LIBELLE></RECORD><RECORD><THESAURUS_ID>2821</THESAURUS_ID><LIBELLE>sosiaalinen kehys</LIBELLE></RECORD><RECORD><THESAURUS_ID>2826</THESAURUS_ID><LIBELLE>sosiaalinen elämä</LIBELLE></RECORD><RECORD><THESAURUS_ID>2831</THESAURUS_ID><LIBELLE>kulttuuri ja uskonto</LIBELLE></RECORD><RECORD><THESAURUS_ID>2836</THESAURUS_ID><LIBELLE>sosiaalinen suojelu</LIBELLE></RECORD><RECORD><THESAURUS_ID>2841</THESAURUS_ID><LIBELLE>terveys</LIBELLE></RECORD><RECORD><THESAURUS_ID>2846</THESAURUS_ID><LIBELLE>rakentaminen ja yhdyskuntasuunnittelu</LIBELLE></RECORD><RECORD><THESAURUS_ID>3206</THESAURUS_ID><LIBELLE>koulutus</LIBELLE></RECORD><RECORD><THESAURUS_ID>3211</THESAURUS_ID><LIBELLE>opetus</LIBELLE></RECORD><RECORD><THESAURUS_ID>3216</THESAURUS_ID><LIBELLE>opetusjärjestelmä</LIBELLE></RECORD><RECORD><THESAURUS_ID>3221</THESAURUS_ID><LIBELLE>asiakirjat</LIBELLE></RECORD><RECORD><THESAURUS_ID>3226</THESAURUS_ID><LIBELLE>viestintä</LIBELLE></RECORD><RECORD><THESAURUS_ID>3231</THESAURUS_ID><LIBELLE>tieto ja tiedonkäsittely</LIBELLE></RECORD><RECORD><THESAURUS_ID>3236</THESAURUS_ID><LIBELLE>tietotekniikka ja tietojenkäsittely</LIBELLE></RECORD><RECORD><THESAURUS_ID>3606</THESAURUS_ID><LIBELLE>luonnontieteet ja soveltavat tieteet</LIBELLE></RECORD><RECORD><THESAURUS_ID>3611</THESAURUS_ID><LIBELLE>humanistiset tieteet</LIBELLE></RECORD><RECORD><THESAURUS_ID>4006</THESAURUS_ID><LIBELLE>yrityksen organisaatio</LIBELLE></RECORD><RECORD><THESAURUS_ID>4011</THESAURUS_ID><LIBELLE>yritysmuoto</LIBELLE></RECORD><RECORD><THESAURUS_ID>4016</THESAURUS_ID><LIBELLE>yhtiön oikeudellinen muoto</LIBELLE></RECORD><RECORD><THESAURUS_ID>4021</THESAURUS_ID><LIBELLE>hallinnollinen johtaminen</LIBELLE></RECORD><RECORD><THESAURUS_ID>4026</THESAURUS_ID><LIBELLE>laskentatoimi</LIBELLE></RECORD><RECORD><THESAURUS_ID>4031</THESAURUS_ID><LIBELLE>kilpailu</LIBELLE></RECORD><RECORD><THESAURUS_ID>4406</THESAURUS_ID><LIBELLE>työllisyys</LIBELLE></RECORD><RECORD><THESAURUS_ID>4411</THESAURUS_ID><LIBELLE>työmarkkinat</LIBELLE></RECORD><RECORD><THESAURUS_ID>4416</THESAURUS_ID><LIBELLE>työolot ja työn järjestäminen</LIBELLE></RECORD><RECORD><THESAURUS_ID>4421</THESAURUS_ID><LIBELLE>henkilöstö- ja palkkahallinto</LIBELLE></RECORD><RECORD><THESAURUS_ID>4426</THESAURUS_ID><LIBELLE>työmarkkinasuhteet ja työoikeus</LIBELLE></RECORD><RECORD><THESAURUS_ID>4806</THESAURUS_ID><LIBELLE>liikennepolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>4811</THESAURUS_ID><LIBELLE>kuljetusjärjestelyt</LIBELLE></RECORD><RECORD><THESAURUS_ID>4816</THESAURUS_ID><LIBELLE>maaliikenne</LIBELLE></RECORD><RECORD><THESAURUS_ID>4821</THESAURUS_ID><LIBELLE>meri- ja jokiliikenne</LIBELLE></RECORD><RECORD><THESAURUS_ID>4826</THESAURUS_ID><LIBELLE>ilma- ja avaruusliikenne</LIBELLE></RECORD><RECORD><THESAURUS_ID>5206</THESAURUS_ID><LIBELLE>ympäristöpolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>5211</THESAURUS_ID><LIBELLE>luonnonympäristö</LIBELLE></RECORD><RECORD><THESAURUS_ID>5216</THESAURUS_ID><LIBELLE>ympäristön laadun huononeminen</LIBELLE></RECORD><RECORD><THESAURUS_ID>5606</THESAURUS_ID><LIBELLE>maatalouspolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>5611</THESAURUS_ID><LIBELLE>maatalouden rakenteet ja tuotanto</LIBELLE></RECORD><RECORD><THESAURUS_ID>5616</THESAURUS_ID><LIBELLE>maatalousjärjestelmä</LIBELLE></RECORD><RECORD><THESAURUS_ID>5621</THESAURUS_ID><LIBELLE>maatalousmaan viljely</LIBELLE></RECORD><RECORD><THESAURUS_ID>5626</THESAURUS_ID><LIBELLE>maataloustuotannon välineet</LIBELLE></RECORD><RECORD><THESAURUS_ID>5631</THESAURUS_ID><LIBELLE>maatalouselinkeino</LIBELLE></RECORD><RECORD><THESAURUS_ID>5636</THESAURUS_ID><LIBELLE>metsätalous</LIBELLE></RECORD><RECORD><THESAURUS_ID>5641</THESAURUS_ID><LIBELLE>kalastus</LIBELLE></RECORD><RECORD><THESAURUS_ID>6006</THESAURUS_ID><LIBELLE>kasvituotteet</LIBELLE></RECORD><RECORD><THESAURUS_ID>6011</THESAURUS_ID><LIBELLE>eläintuote</LIBELLE></RECORD><RECORD><THESAURUS_ID>6016</THESAURUS_ID><LIBELLE>jalostettu maataloustuote</LIBELLE></RECORD><RECORD><THESAURUS_ID>6021</THESAURUS_ID><LIBELLE>juomat ja sokeri</LIBELLE></RECORD><RECORD><THESAURUS_ID>6026</THESAURUS_ID><LIBELLE>elintarvike</LIBELLE></RECORD><RECORD><THESAURUS_ID>6031</THESAURUS_ID><LIBELLE>maatalouselintarvikkeet</LIBELLE></RECORD><RECORD><THESAURUS_ID>6036</THESAURUS_ID><LIBELLE>elintarviketeknologia</LIBELLE></RECORD><RECORD><THESAURUS_ID>6406</THESAURUS_ID><LIBELLE>tuotanto</LIBELLE></RECORD><RECORD><THESAURUS_ID>6411</THESAURUS_ID><LIBELLE>teknologia ja tekninen sääntely</LIBELLE></RECORD><RECORD><THESAURUS_ID>6416</THESAURUS_ID><LIBELLE>tutkimus ja immateriaalioikeus</LIBELLE></RECORD><RECORD><THESAURUS_ID>6606</THESAURUS_ID><LIBELLE>energiapolitiikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>6611</THESAURUS_ID><LIBELLE>hiili- ja kaivosteollisuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>6616</THESAURUS_ID><LIBELLE>öljyteollisuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>6621</THESAURUS_ID><LIBELLE>ydin- ja voimalateollisuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>6626</THESAURUS_ID><LIBELLE>pehmeä energia</LIBELLE></RECORD><RECORD><THESAURUS_ID>6806</THESAURUS_ID><LIBELLE>teollisuuspolitiikka ja teollisuuden rakenteet</LIBELLE></RECORD><RECORD><THESAURUS_ID>6811</THESAURUS_ID><LIBELLE>kemia</LIBELLE></RECORD><RECORD><THESAURUS_ID>6816</THESAURUS_ID><LIBELLE>metallurgia ja terästeollisuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>6821</THESAURUS_ID><LIBELLE>konepajateollisuus</LIBELLE></RECORD><RECORD><THESAURUS_ID>6826</THESAURUS_ID><LIBELLE>elektroniikka ja sähkötekniikka</LIBELLE></RECORD><RECORD><THESAURUS_ID>6831</THESAURUS_ID><LIBELLE>talonrakennus- ja julkinen rakennustoiminta</LIBELLE></RECORD><RECORD><THESA
