=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/used_for.dtd
<!-- DTD for the synonyms (used-for)  -->
<!ELEMENT USED_FOR (RECORD+)>
<!ATTLIST USED_FOR
			LNG					CDATA		#REQUIRED
			VERSION				CDATA		#REQUIRED >
<!-- language and EUROVOC release number -->

<!ELEMENT RECORD (DESCRIPTEUR_ID, UF)>
<!-- The relation of a non-PT to its concept
The relation is language specific
ev:ThesaurusConcept[xl:altLabel/xl:literalForm/@xml:lang = /DESCRIPTEUR/@LNG] 
-->

<!ELEMENT DESCRIPTEUR_ID	(#PCDATA)>
<!-- The id of the concept
The PT of this concept must refer to the synonyms using UF: <value of non-PT>+
ev:ThesaurusConcept/dc:identifer 
-->

<!ELEMENT UF ((UF_EL,DEF?)+)>
<!-- The synonyms
Each synonym 
- must refer to its PT using USE: <value of PT>
- must refer its occasional definition note - DEF

group by ev:ThesaurusConcept/dc:identifer -->

<!ELEMENT UF_EL				(#PCDATA)>
<!-- The non-PT value
ev:ThesaurusConcept/xl:altLabel[xml:lang = /DESCRIPTEUR/@LNG]/xl:literalForm 
-->
<!ATTLIST UF_EL
			FORM		(fullname | shortname | acronym)		#IMPLIED>
<!-- 
occasional indication of the form of a non-PT -->

<!ELEMENT DEF				(#PCDATA)>
<!-- The definition note of a non-PT (UF_EL)
string(ev:ThesaurusConcept/xl:altLabel[xml:lang = /DESCRIPTEUR/@LNG]/skos:definition) -->

=== simonegasperoni/MSc_thesis_tex/code/src/main/resources/eurovoc/eurovoc_xml/uf_bg.xml
<?xml version="1.0" encoding ="UTF-8"?>
<!DOCTYPE USED_FOR SYSTEM "used_for.dtd">
<USED_FOR LNG="bg" VERSION="4.5"><RECORD><DESCRIPTEUR_ID>1002</DESCRIPTEUR_ID><UF><UF_EL>дългосрочни инвестиции</UF_EL><UF_EL>фонд за дългосрочни инвестиции</UF_EL><UF_EL>ЕФДИ</UF_EL><UF_EL>европейски фонд за дългосрочни инвестиции</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1005</DESCRIPTEUR_ID><UF><UF_EL>финансиране на Общността</UF_EL><UF_EL>финансиране на Европейския съюз</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1019</DESCRIPTEUR_ID><UF><UF_EL>Република Финландия</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1022</DESCRIPTEUR_ID><UF><UF_EL>Детски фонд на Обединените нации</UF_EL><UF_EL>Детски фонд на ООН</UF_EL><UF_EL>Международен детски фонд на ООН за спешна помощ на децата</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1043</DESCRIPTEUR_ID><UF><UF_EL>МВФ</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1044</DESCRIPTEUR_ID><UF><UF_EL>МАСС</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1045</DESCRIPTEUR_ID><UF><UF_EL>UNFPA</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1052</DESCRIPTEUR_ID><UF><UF_EL>фондове на ЕС</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1056</DESCRIPTEUR_ID><UF><UF_EL>ЕФРР</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1083</DESCRIPTEUR_ID><UF><UF_EL>административни разходи</UF_EL><UF_EL>представителни разходи</UF_EL><UF_EL>разходи за управление</UF_EL><UF_EL>финансови разходи</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1085</DESCRIPTEUR_ID><UF><UF_EL>Френска република</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1086</DESCRIPTEUR_ID><UF><UF_EL>Френски отвъдморски департаменти</UF_EL><UF_EL>отвъдморски департаменти на Франция</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1087</DESCRIPTEUR_ID><UF><UF_EL>френски отвъдморски територии</UF_EL><UF_EL>отвъдморски територии на Франция</UF_EL><UF_EL>отвъдморски територии на Френската република</UF_EL><UF_EL>териториални общности на Френската република</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1091</DESCRIPTEUR_ID><UF><UF_EL>безмитен внос</UF_EL><UF_EL>митническо освобождаване</UF_EL><UF_EL>неосвобождаване от вносни митни сборове</UF_EL><UF_EL>освобождаване от вносни митни сборове</UF_EL><UF_EL>освобождаване от митнически такси при внос</UF_EL><UF_EL>освобождаване от такси</UF_EL><UF_EL>разрешен безмитен внос за пътуващи</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1094</DESCRIPTEUR_ID><UF><UF_EL>Латиноамериканска асоциация за интеграция</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1105</DESCRIPTEUR_ID><UF><UF_EL>страни от Асоциацията за интеграция на Латинска Америка</UF_EL><UF_EL>държави от Латиноамериканската асоциация за интеграция</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>111</DESCRIPTEUR_ID><UF><UF_EL>Конго-Бразавил</UF_EL><UF_EL>Република Конго</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1124</DESCRIPTEUR_ID><UF><UF_EL>Република Габон</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1125</DESCRIPTEUR_ID><UF><UF_EL>Република Албания</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1128</DESCRIPTEUR_ID><UF><UF_EL>Република Гамбия</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>115</DESCRIPTEUR_ID><UF><UF_EL>съвет на директорите</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>116</DESCRIPTEUR_ID><UF><UF_EL>Съвет на асоциацията на ЕО</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1166</DESCRIPTEUR_ID><UF><UF_EL>Република Гана</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>118</DESCRIPTEUR_ID><UF><UF_EL>СКС</UF_EL><UF_EL FORM="fullname">Управителен комитет за висше образование и научни изследвания</UF_EL><UF_EL FORM="acronym">CDESR</UF_EL><UF_EL FORM="fullname">Управителен комитет за култура</UF_EL><UF_EL FORM="acronym">CDCULT</UF_EL><UF_EL FORM="fullname">Управителен комитет за културно наследство</UF_EL><UF_EL FORM="acronym">CDPAT</UF_EL><UF_EL FORM="fullname">Управителен комитет за просвета</UF_EL><UF_EL FORM="acronym">CDED</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1182</DESCRIPTEUR_ID><UF><UF_EL>Република Гърция</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1190</DESCRIPTEUR_ID><UF><UF_EL>група на държавите от Андите</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1194</DESCRIPTEUR_ID><UF><UF_EL>Г-10</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1195</DESCRIPTEUR_ID><UF><UF_EL>ADR</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1196</DESCRIPTEUR_ID><UF><UF_EL>Народна демократична република Алжир</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>120</DESCRIPTEUR_ID><UF><UF_EL>АТС</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1208</DESCRIPTEUR_ID><UF><UF_EL>Република Гватемала</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1216</DESCRIPTEUR_ID><UF><UF_EL>Република Гвинея</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1217</DESCRIPTEUR_ID><UF><UF_EL>Република Гвинея-Бисау</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1218</DESCRIPTEUR_ID><UF><UF_EL>Република Екваториална Гвинея</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1219</DESCRIPTEUR_ID><UF><UF_EL>Кооперативна република Гвиана</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1220</DESCRIPTEUR_ID><UF><UF_EL>Френска Гвинея</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1221</DESCRIPTEUR_ID><UF><UF_EL>местообитание на човека</UF_EL><UF_EL>селища на човека</UF_EL><UF_EL>човешко селище</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1222</DESCRIPTEUR_ID><UF><UF_EL>селска среда</UF_EL><UF_EL>селско пространство</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1223</DESCRIPTEUR_ID><UF><UF_EL>градска среда</UF_EL><UF_EL>градски жилищен комплекс</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1228</DESCRIPTEUR_ID><UF><UF_EL>Република Хаити</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1230</DESCRIPTEUR_ID><UF><UF_EL>Хамбург (Свободен и ханзеатски град)</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1236</DESCRIPTEUR_ID><UF><UF_EL>Горна Волта</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1239</DESCRIPTEUR_ID><UF><UF_EL>Хесен (провинция)</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1247</DESCRIPTEUR_ID><UF><UF_EL>управляващо дружество</UF_EL><UF_EL>холдингово дружество</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1252</DESCRIPTEUR_ID><UF><UF_EL>сертификат за съответствие</UF_EL><UF_EL>сертифициране за качество</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1253</DESCRIPTEUR_ID><UF><UF_EL>Република Хондурас</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1254</DESCRIPTEUR_ID><UF><UF_EL>Специален административен район Хонконг</UF_EL><UF_EL>Специален административен район на Китайската народна република Хонконг</UF_EL><UF_EL>САР Хонконг</UF_EL><UF_EL>Хонконг (Китай)</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1290</DESCRIPTEUR_ID><UF><UF_EL>Англо-нормандски острови</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1294</DESCRIPTEUR_ID><UF><UF_EL>Ферьорски острови</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1298</DESCRIPTEUR_ID><UF><UF_EL>острови Турк и Кайкос</UF_EL><UF_EL>острови Тюрк и Кайкос</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1299</DESCRIPTEUR_ID><UF><UF_EL>Британски Вирджински острови</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1308</DESCRIPTEUR_ID><UF><UF_EL>предишна ГДР</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1318</DESCRIPTEUR_ID><UF><UF_EL>Федерална република Германия</UF_EL><UF_EL>ФРГ</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1338</DESCRIPTEUR_ID><UF><UF_EL>Република Индия</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1355</DESCRIPTEUR_ID><UF><UF_EL>Република Индонезия</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1356</DESCRIPTEUR_ID><UF><UF_EL>деиндустриализация</UF_EL><UF_EL>политика на индустриализация</UF_EL><UF_EL>създаване на промишленост</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1410</DESCRIPTEUR_ID><UF><UF_EL>дизайн на машини</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1449</DESCRIPTEUR_ID><UF><UF_EL>Европейски синдикален институт за изследвания, обучение, здраве и безопасност</UF_EL><UF_EL>ЕСИ – ИОЗБ</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1450</DESCRIPTEUR_ID><UF><UF_EL>институция на АЦП — ЕО</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1455</DESCRIPTEUR_ID><UF><UF_EL>специализирана агенция на ООН</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1456</DESCRIPTEUR_ID><UF><UF_EL>модернизация на жилищния фонд</UF_EL><UF_EL>модернизиране на жилището</UF_EL><UF_EL>обновяване на жизненото пространство</UF_EL><UF_EL>обновяване на жилищния фонд</UF_EL><UF_EL>обновяване на сградния фонд</UF_EL><UF_EL>подобряване на жизненото пространство</UF_EL><UF_EL>подобряване на обитаемата среда</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1460</DESCRIPTEUR_ID><UF><UF_EL>финансов инструмент на Европейския съюз</UF_EL><UF_EL>Финансов инструмент но Общността</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1474</DESCRIPTEUR_ID><UF><UF_EL>конвенция ЕС-трети държави</UF_EL><UF_EL>международно споразумение (ЕС)</UF_EL><UF_EL>споразумение на Европейския съюз</UF_EL><UF_EL>споразумение на ЕО</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1490</DESCRIPTEUR_ID><UF><UF_EL>инвестиция на Общността</UF_EL><UF_EL>инвестиция на Европейския съюз</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1500</DESCRIPTEUR_ID><UF><UF_EL>Република Ирак</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1501</DESCRIPTEUR_ID><UF><UF_EL>Ислямска република Иран</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1504</DESCRIPTEUR_ID><UF><UF_EL>Ейре</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1507</DESCRIPTEUR_ID><UF><UF_EL>UNRISD</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1509</DESCRIPTEUR_ID><UF><UF_EL>Република Исландия</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1510</DESCRIPTEUR_ID><UF><UF_EL>Международна организация по стандартизация</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1518</DESCRIPTEUR_ID><UF><UF_EL>Държавата Израел</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1519</DESCRIPTEUR_ID><UF><UF_EL>Италианска република</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1528</DESCRIPTEUR_ID><UF><UF_EL>младежи</UF_EL><UF_EL>непълнолетно лице</UF_EL><UF_EL>юноша</UF_EL><UF_EL>юношество</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1532</DESCRIPTEUR_ID><UF><UF_EL>Хашемитско кралство Йордания</UF_EL></UF></RECORD><RECORD><DESCRIPTEUR_ID>1551</DESCRIPTEUR_ID><UF><UF_EL>прецедентно право на ЕО</UF_EL></UF></RECORD><
